sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Temperature"
      filters:
        - offset: -30.0
    humidity:
      name: "Humidity"
      filters:
        - offset: 0
    update_interval: 10s